# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 85c643d69ea41675c7bd210b4fa9247979b9bd6f7676a548421eed9a279066d97d903c01981fb0a8cc3a23904e94959d0db422e5c41d396a1211d7cbf248aea4

test:
  secret_key_base: 351d2fd42049a3fbe8db990d33c7fcb20aa2f828add9a2171a09046b7540ede62bf98f0bc27877ab1cd356abba8a81b15d3b59112721d4a71605d7492c451952

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
